### ISSUE TITLE
validation.captcha

### ISSUE THREAD

**Issue by felixlandicho** [anhskohbo/no-captcha#24] opened 2015-09-23 12:42 UTC
Hi,

Why do I receive this error? even if the noCaptcha is a green check.

"g-recaptcha-response" => array:1 [
     0 => "validation.captcha"
]

Thanks

**Comment by anhskohbo** [comment] 2015-09-24 12:55
I'll check and reply you soon

**Comment by d3rd4v1d** [comment] 2015-09-24 18:14
I have same issue.

**Comment by Lotuashvili** [comment] 2015-11-28 19:50
@anhskohbo I have the same issue, please answer :)

**Comment by d3rd4v1d** [comment] 2015-11-29 09:07
I am using https://github.com/CrazyInventor/laravel5-recaptcha2 now. That works for me.

**Comment by lehnen** [comment] 2015-12-18 20:15
Same for me.
I run it under Homestead witch success. On my provider (Hosteurope) the same code fails with above message.

**Comment by Lotuashvili** [comment] 2015-12-18 20:16
@lehnen I had incorrect secret key copied in my configuration file, please double check :)

Good luck

**Comment by lehnen** [comment] 2015-12-18 20:26
@Lotuashvili Nice quick answer ;)
I checked the keys and they are identical on both sides. Also both domains are mentioned in Googles reCapcha console as valid for the keys.

**Comment by lehnen** [comment] 2015-12-19 08:39
Fix for me: I wanted to use ReCaptcha, not NoCaptcha. Since the documentation of reCaptcha states to use POST parameter for validation (https://developers.google.com/recaptcha/docs/verify#api-request) I implemented it by myself, based on this code. I used Guzzle to make a POST request instaed of the GET request used by the original code an it works.

**Comment by nhtua** [comment] 2016-05-29 09:36
Maybe you are trying to validate one recaptcha's response twice (when resubmit form). Every result key is one-time used.

**Comment by anhskohbo** [comment] 2016-08-24 16:24
Fixed with latest commit.

**Closed by anhskohbo** 2016-08-24 16:24 UTC

**Comment by Tarasovych** [comment] 2018-04-12 11:14
Same issue.
I get `validation.captcha` in both situations:

* having non-valid `NOCAPTCHA_SECRET`, valid `NOCAPTCHA_SITEKEY`
* having valid `NOCAPTCHA_SECRET`, non-valid `NOCAPTCHA_SITEKEY`

How can I set [custom validation message](https://github.com/anhskohbo/no-captcha#custom-validation-message) for these cases?

**Comment by Tarasovych** [comment] 2018-04-22 19:37
@anhskohbo Still same issue.
I get `validation.captcha` in both situations:

* having non-valid `NOCAPTCHA_SECRET`, valid `NOCAPTCHA_SITEKEY`
* having valid `NOCAPTCHA_SECRET`, non-valid `NOCAPTCHA_SITEKEY`

Can I set [custom validation message](https://github.com/anhskohbo/no-captcha#custom-validation-message) for this case?

**Comment by Tarasovych** [comment] 2018-07-11 20:04
Anybody here?

**Comment by mpge** [comment] 2018-09-13 22:10
Can confirm, I receive this as well with the current version.

**Comment by Tarasovych** [comment] 2018-09-13 22:17
Still have a problem too.

**Comment by mpge** [comment] 2018-09-13 22:29
Checked my secret/private key, turns out Google for whatever reason reset the key on me.

Maybe check that.

**Comment by waqar-husain** [comment] 2019-07-29 10:52
still getting this issue with laravel 5.8

**Comment by khairulhasanmd** [comment] 2020-06-23 04:03
@iwaqarhussain 
I can confirm, that works. Thanks.

**Comment by mpge** [comment] 2020-06-23 04:40
> @iwaqarhussain
> I can confirm, that works. Thanks.

I'm assuming this effectively just removes the validation for the captcha - hence, if the captcha is invalid/not correctly filled, it won't actually throw an error which is entirely the point of the captcha.

Not sure i'd reco this.

**Comment by iwaqarhussain** [comment] 2020-06-23 05:01
> > @iwaqarhussain
> > I can confirm, that works. Thanks.
> 
> I'm assuming this effectively just removes the validation for the captcha - hence, if the captcha is invalid/not correctly filled, it won't actually throw an error which is entirely the point of the captcha.
> 
> Not sure i'd reco this.

No, that's not the way this works. 

It do what it's supposed to do

**Comment by mpge** [comment] 2020-06-23 07:19
> > > @iwaqarhussain
> > > I can confirm, that works. Thanks.
> > 
> > 
> > I'm assuming this effectively just removes the validation for the captcha - hence, if the captcha is invalid/not correctly filled, it won't actually throw an error which is entirely the point of the captcha.
> > Not sure i'd reco this.
> 
> No, that's not the way this works.
> 
> It do what it's supposed to do

You may get client side validation on behalf of google, but in terms of your own actual server side validation, if you have no other code to validate the captcha, it will not be validated on your end (server side) AFAIK.

If you don't use the "captcha" rule, the function verifyResponse will not be hit. verifyResponse is the function that effectively checks with Google to ensure that the token provided through the post requests matches and is valid.

There should be another solution other than simply removing the rule all-together. Otherwise your captcha may not be foolproof.
You can see that someone commented below on the solution on StackOverflow.

**Comment by mrsnax** [comment] 2024-11-09 17:21
Hi

Got a validation.captcha error today, does anyone have a solution?
